INSERT INTO resources (name, description) VALUES 
('project', 'Project management'), 
('code', 'Source code'), 
('architecture', 'System architecture'),
('deployment', 'Code deployment'),
('security', 'Security resources'),
('database', 'Database access'),
('api', 'API interfaces'),
('ui', 'User interface'),
('test', 'Testing tools'),
('documentation', 'Documentation'),
('infrastructure', 'Infrastructure'),
('user', 'User management'),
('role', 'Role management'),
('analytics', 'Data analytics'),
('budget', 'Budget'),
('content', 'Content resources'),
('mobile', 'Mobile apps'),
('ai', 'AI tools'),
('cloud', 'Cloud services'),
('task_group', 'Task groups'),
('task', 'Tasks');
