INSERT INTO resources (Name, Description) VALUES 
    ('project', 'Project management resources'),
    ('code', 'Source code and repositories'),
    ('architecture', 'System architecture and design'),
    ('deployment', 'Deployment and release management'),
    ('security', 'Security-related resources'),
    ('database', 'Database management and access'),
    ('api', 'API management and access'),
    ('ui', 'User interface components'),
    ('test', 'Testing and QA resources'),
    ('documentation', 'Project documentation'),
    ('infrastructure', 'Infrastructure management'),
    ('user', 'User management'),
    ('role', 'Role management'),
    ('analytics', 'Analytics and reporting'),
    ('budget', 'Budget management'),
    ('design', 'UI/UX design resources'),
    ('content', 'Content management'),
    ('mobile', 'Mobile application resources'),
    ('ai', 'Artificial Intelligence resources'),
    ('cloud', 'Cloud infrastructure'),
    ('performance', 'Performance testing resources'),
    ('security_test', 'Security testing resources'),
    ('task_banner', 'Task banner management resources'),
    ('task', 'Task management resources');
